"""
Circuit Metadata
================
Static lookup table of F1 circuit information keyed by FastF1 Location field.

Updated for the 2025 season calendar.  Lap records reflect the fastest race
lap set at each venue (not qualifying).

Each entry includes GPS coordinates (lat/lon) for weather lookups.
"""

CIRCUIT_DATA: dict[str, dict] = {
    "Sakhir": {
        "circuit_name": "Bahrain International Circuit",
        "track_length_km": 5.412,
        "laps": 57,
        "lap_record": {"time": "1:31.447", "driver": "Pedro de la Rosa", "year": 2005},
        "first_gp": 2004,
        "circuit_type": "Purpose-built",
        "lat": 26.0325,
        "lon": 50.5106,
    },
    "Jeddah": {
        "circuit_name": "Jeddah Corniche Circuit",
        "track_length_km": 6.174,
        "laps": 50,
        "lap_record": {"time": "1:30.734", "driver": "Lewis Hamilton", "year": 2021},
        "first_gp": 2021,
        "circuit_type": "Street circuit",
        "lat": 21.6319,
        "lon": 39.1044,
    },
    "Melbourne": {
        "circuit_name": "Albert Park Circuit",
        "track_length_km": 5.278,
        "laps": 58,
        "lap_record": {"time": "1:19.813", "driver": "Charles Leclerc", "year": 2024},
        "first_gp": 1996,
        "circuit_type": "Street circuit",
        "lat": -37.8497,
        "lon": 144.9680,
    },
    "Suzuka": {
        "circuit_name": "Suzuka International Racing Course",
        "track_length_km": 5.807,
        "laps": 53,
        "lap_record": {"time": "1:30.983", "driver": "Lewis Hamilton", "year": 2019},
        "first_gp": 1987,
        "circuit_type": "Purpose-built",
        "lat": 34.8431,
        "lon": 136.5407,
    },
    "Shanghai": {
        "circuit_name": "Shanghai International Circuit",
        "track_length_km": 5.451,
        "laps": 56,
        "lap_record": {"time": "1:32.238", "driver": "Michael Schumacher", "year": 2004},
        "first_gp": 2004,
        "circuit_type": "Purpose-built",
        "lat": 31.3389,
        "lon": 121.2198,
    },
    "Miami": {
        "circuit_name": "Miami International Autodrome",
        "track_length_km": 5.412,
        "laps": 57,
        "lap_record": {"time": "1:29.708", "driver": "Max Verstappen", "year": 2023},
        "first_gp": 2022,
        "circuit_type": "Street circuit",
        "lat": 25.9581,
        "lon": -80.2389,
    },
    "Miami Gardens": {
        "circuit_name": "Miami International Autodrome",
        "track_length_km": 5.412,
        "laps": 57,
        "lap_record": {"time": "1:29.708", "driver": "Max Verstappen", "year": 2023},
        "first_gp": 2022,
        "circuit_type": "Street circuit",
        "lat": 25.9581,
        "lon": -80.2389,
    },
    "Imola": {
        "circuit_name": "Autodromo Enzo e Dino Ferrari",
        "track_length_km": 4.909,
        "laps": 63,
        "lap_record": {"time": "1:15.484", "driver": "Lewis Hamilton", "year": 2020},
        "first_gp": 1980,
        "circuit_type": "Purpose-built",
        "lat": 44.3439,
        "lon": 11.7167,
    },
    "Monte Carlo": {
        "circuit_name": "Circuit de Monaco",
        "track_length_km": 3.337,
        "laps": 78,
        "lap_record": {"time": "1:12.909", "driver": "Lewis Hamilton", "year": 2021},
        "first_gp": 1950,
        "circuit_type": "Street circuit",
        "lat": 43.7347,
        "lon": 7.4206,
    },
    "Monaco": {
        "circuit_name": "Circuit de Monaco",
        "track_length_km": 3.337,
        "laps": 78,
        "lap_record": {"time": "1:12.909", "driver": "Lewis Hamilton", "year": 2021},
        "first_gp": 1950,
        "circuit_type": "Street circuit",
        "lat": 43.7347,
        "lon": 7.4206,
    },
    "Barcelona": {
        "circuit_name": "Circuit de Barcelona-Catalunya",
        "track_length_km": 4.657,
        "laps": 66,
        "lap_record": {"time": "1:16.330", "driver": "Max Verstappen", "year": 2023},
        "first_gp": 1991,
        "circuit_type": "Purpose-built",
        "lat": 41.5700,
        "lon": 2.2611,
    },
    "Montréal": {
        "circuit_name": "Circuit Gilles Villeneuve",
        "track_length_km": 4.361,
        "laps": 70,
        "lap_record": {"time": "1:13.078", "driver": "Valtteri Bottas", "year": 2019},
        "first_gp": 1978,
        "circuit_type": "Semi-street circuit",
        "lat": 45.5017,
        "lon": -73.5228,
    },
    "Spielberg": {
        "circuit_name": "Red Bull Ring",
        "track_length_km": 4.318,
        "laps": 71,
        "lap_record": {"time": "1:05.619", "driver": "Carlos Sainz", "year": 2020},
        "first_gp": 1970,
        "circuit_type": "Purpose-built",
        "lat": 47.2197,
        "lon": 14.7647,
    },
    "Silverstone": {
        "circuit_name": "Silverstone Circuit",
        "track_length_km": 5.891,
        "laps": 52,
        "lap_record": {"time": "1:27.097", "driver": "Max Verstappen", "year": 2020},
        "first_gp": 1950,
        "circuit_type": "Purpose-built",
        "lat": 52.0786,
        "lon": -1.0169,
    },
    "Mogyoród": {
        "circuit_name": "Hungaroring",
        "track_length_km": 4.381,
        "laps": 70,
        "lap_record": {"time": "1:16.627", "driver": "Lewis Hamilton", "year": 2020},
        "first_gp": 1986,
        "circuit_type": "Purpose-built",
        "lat": 47.5789,
        "lon": 19.2486,
    },
    "Budapest": {
        "circuit_name": "Hungaroring",
        "track_length_km": 4.381,
        "laps": 70,
        "lap_record": {"time": "1:16.627", "driver": "Lewis Hamilton", "year": 2020},
        "first_gp": 1986,
        "circuit_type": "Purpose-built",
        "lat": 47.5789,
        "lon": 19.2486,
    },
    "Spa-Francorchamps": {
        "circuit_name": "Circuit de Spa-Francorchamps",
        "track_length_km": 7.004,
        "laps": 44,
        "lap_record": {"time": "1:46.286", "driver": "Valtteri Bottas", "year": 2018},
        "first_gp": 1950,
        "circuit_type": "Purpose-built",
        "lat": 50.4372,
        "lon": 5.9714,
    },
    "Stavelot": {
        "circuit_name": "Circuit de Spa-Francorchamps",
        "track_length_km": 7.004,
        "laps": 44,
        "lap_record": {"time": "1:46.286", "driver": "Valtteri Bottas", "year": 2018},
        "first_gp": 1950,
        "circuit_type": "Purpose-built",
        "lat": 50.4372,
        "lon": 5.9714,
    },
    "Zandvoort": {
        "circuit_name": "Circuit Zandvoort",
        "track_length_km": 4.259,
        "laps": 72,
        "lap_record": {"time": "1:11.097", "driver": "Lewis Hamilton", "year": 2021},
        "first_gp": 1952,
        "circuit_type": "Purpose-built",
        "lat": 52.3888,
        "lon": 4.5409,
    },
    "Monza": {
        "circuit_name": "Autodromo Nazionale Monza",
        "track_length_km": 5.793,
        "laps": 53,
        "lap_record": {"time": "1:21.046", "driver": "Rubens Barrichello", "year": 2004},
        "first_gp": 1950,
        "circuit_type": "Purpose-built",
        "lat": 45.6156,
        "lon": 9.2811,
    },
    "Baku": {
        "circuit_name": "Baku City Circuit",
        "track_length_km": 6.003,
        "laps": 51,
        "lap_record": {"time": "1:43.009", "driver": "Charles Leclerc", "year": 2019},
        "first_gp": 2016,
        "circuit_type": "Street circuit",
        "lat": 40.3725,
        "lon": 49.8533,
    },
    "Marina Bay": {
        "circuit_name": "Marina Bay Street Circuit",
        "track_length_km": 4.940,
        "laps": 62,
        "lap_record": {"time": "1:35.867", "driver": "Lewis Hamilton", "year": 2023},
        "first_gp": 2008,
        "circuit_type": "Street circuit",
        "lat": 1.2914,
        "lon": 103.8640,
    },
    "Singapore": {
        "circuit_name": "Marina Bay Street Circuit",
        "track_length_km": 4.940,
        "laps": 62,
        "lap_record": {"time": "1:35.867", "driver": "Lewis Hamilton", "year": 2023},
        "first_gp": 2008,
        "circuit_type": "Street circuit",
        "lat": 1.2914,
        "lon": 103.8640,
    },
    "Austin": {
        "circuit_name": "Circuit of the Americas",
        "track_length_km": 5.513,
        "laps": 56,
        "lap_record": {"time": "1:36.169", "driver": "Charles Leclerc", "year": 2019},
        "first_gp": 2012,
        "circuit_type": "Purpose-built",
        "lat": 30.1328,
        "lon": -97.6411,
    },
    "Mexico City": {
        "circuit_name": "Autódromo Hermanos Rodríguez",
        "track_length_km": 4.304,
        "laps": 71,
        "lap_record": {"time": "1:17.774", "driver": "Valtteri Bottas", "year": 2021},
        "first_gp": 1963,
        "circuit_type": "Purpose-built",
        "lat": 19.4042,
        "lon": -99.0907,
    },
    "São Paulo": {
        "circuit_name": "Autódromo José Carlos Pace (Interlagos)",
        "track_length_km": 4.309,
        "laps": 71,
        "lap_record": {"time": "1:10.540", "driver": "Valtteri Bottas", "year": 2018},
        "first_gp": 1973,
        "circuit_type": "Purpose-built",
        "lat": -23.7036,
        "lon": -46.6997,
    },
    "Las Vegas": {
        "circuit_name": "Las Vegas Strip Circuit",
        "track_length_km": 6.201,
        "laps": 50,
        "lap_record": {"time": "1:35.490", "driver": "Oscar Piastri", "year": 2024},
        "first_gp": 2023,
        "circuit_type": "Street circuit",
        "lat": 36.1147,
        "lon": -115.1728,
    },
    "Lusail": {
        "circuit_name": "Lusail International Circuit",
        "track_length_km": 5.419,
        "laps": 57,
        "lap_record": {"time": "1:24.319", "driver": "Max Verstappen", "year": 2023},
        "first_gp": 2021,
        "circuit_type": "Purpose-built",
        "lat": 25.4900,
        "lon": 51.4542,
    },
    "Yas Island": {
        "circuit_name": "Yas Marina Circuit",
        "track_length_km": 5.281,
        "laps": 58,
        "lap_record": {"time": "1:26.103", "driver": "Max Verstappen", "year": 2021},
        "first_gp": 2009,
        "circuit_type": "Purpose-built",
        "lat": 24.4672,
        "lon": 54.6031,
    },
    "Abu Dhabi": {
        "circuit_name": "Yas Marina Circuit",
        "track_length_km": 5.281,
        "laps": 58,
        "lap_record": {"time": "1:26.103", "driver": "Max Verstappen", "year": 2021},
        "first_gp": 2009,
        "circuit_type": "Purpose-built",
        "lat": 24.4672,
        "lon": 54.6031,
    },
    "Yas Marina": {
        "circuit_name": "Yas Marina Circuit",
        "track_length_km": 5.281,
        "laps": 58,
        "lap_record": {"time": "1:26.103", "driver": "Max Verstappen", "year": 2021},
        "first_gp": 2009,
        "circuit_type": "Purpose-built",
        "lat": 24.4672,
        "lon": 54.6031,
    },
    "Madrid": {
        "circuit_name": "Circuito de Madrid IFEMA",
        "track_length_km": 5.473,
        "laps": 66,
        "lap_record": {"time": "-", "driver": "-", "year": 0},
        "first_gp": 2026,
        "circuit_type": "Purpose-built",
        "lat": 40.4680,
        "lon": -3.6163,
    },
}


def get_circuit_info(location: str) -> dict | None:
    """Look up circuit metadata by Location string from the schedule.

    The schedule provides locations like ``"Sakhir, Bahrain"`` -- we try the
    full string first, then just the city part (before the comma).
    """
    if location in CIRCUIT_DATA:
        return CIRCUIT_DATA[location]
    city = location.split(",", maxsplit=1)[0].strip()
    return CIRCUIT_DATA.get(city)


def get_circuit_gps(location: str) -> tuple[float, float] | None:
    """Return (lat, lon) for a circuit, or None if not found."""
    data = CIRCUIT_DATA.get(location)
    if data and "lat" in data and "lon" in data:
        return (data["lat"], data["lon"])
    # Try city-part fallback
    city = location.split(",", maxsplit=1)[0].strip()
    data = CIRCUIT_DATA.get(city)
    if data and "lat" in data and "lon" in data:
        return (data["lat"], data["lon"])
    return None
